name: ZAP Full Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP Full Scan
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: https://thinking-tester-contact-list.herokuapp.com/
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          issue_title: ZAP Full Scan Report
          allow_issue_writing: true
          artifact_name: zap_scan
